In [1]:
import tensorflow as tf

# Tensorflow Constants

In [13]:
x = tf.constant([3,5,7])
x.shape, x.ndim, type(x), x

(TensorShape([3]),
 1,
 tensorflow.python.framework.ops.EagerTensor,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>)

In [11]:
x = tf.constant([[3,5,7],
                 [4,6,8]])
x.shape, x.ndim, type(x), x

(TensorShape([2, 3]),
 2,
 tensorflow.python.framework.ops.EagerTensor,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 7],
        [4, 6, 8]], dtype=int32)>)

In [5]:
x.ndim

2

In [7]:
x = tf.constant([[3,5,7],
                 [4,6,8],
                 [1,3,5]])
x.shape, x.ndim, type(x), x

(TensorShape([3, 3]), 2, tensorflow.python.framework.ops.EagerTensor)

In [10]:
x = tf.constant([[[3,5,7],
                 [4,6,8],
                 [1,3,5],
                 [9,7,5]]])
x.shape, x.ndim, type(x), x

(TensorShape([1, 4, 3]),
 3,
 tensorflow.python.framework.ops.EagerTensor,
 <tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
 array([[[3, 5, 7],
         [4, 6, 8],
         [1, 3, 5],
         [9, 7, 5]]], dtype=int32)>)

In [17]:
x1 = tf.constant([2,3,4])
print("x1:", x1.shape, x1.ndim, type(x1), x1)

x2 = tf.stack([x1,x1])
print("x2:", x2.shape, x2.ndim, type(x2), x2)



x1: (3,) 1 <class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor([2 3 4], shape=(3,), dtype=int32)
x2: (2, 3) 2 <class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(
[[2 3 4]
 [2 3 4]], shape=(2, 3), dtype=int32)


In [19]:
x3 = tf.stack([x2,x2,x2,x2])
print("x3:", x3.shape, x3.ndim, type(x3), x3)

x3: (4, 2, 3) 3 <class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(
[[[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [2 3 4]]], shape=(4, 2, 3), dtype=int32)


In [20]:

x4 = tf.stack([x3,x3])
print("x4:", x4.shape, x4.ndim, type(x4), x4)

x4: (2, 4, 2, 3) 4 <class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(
[[[[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]]


 [[[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]]], shape=(2, 4, 2, 3), dtype=int32)


In [31]:
x = tf.constant([
                 [3,5,7],
                 [2,4,6]
])
print(x.shape)
#print(x[:,1])
y = x[1,:]
print("Y:",y)

(2, 3)
Y: tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [32]:
z = tf.reshape(x, [3,2])
print("z", z)

z tf.Tensor(
[[3 5]
 [7 2]
 [4 6]], shape=(3, 2), dtype=int32)


# Tensorflow Variables

In [34]:
x = tf.Variable(2.0, dtype=tf.float32, name='my_var')
x.shape, x

(TensorShape([]), <tf.Variable 'my_var:0' shape=() dtype=float32, numpy=2.0>)

In [35]:
x.assign(40)
x

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=40.0>

In [36]:
x.assign_add(12)
x

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=52.0>

In [37]:
x.assign_sub(30)
x

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=22.0>

In [46]:
# w*x
x = tf.constant([[2,3], [3,4]])
w = tf.Variable([[2,3], [3,4]])
z = tf.matmul(x,w)
print(x,y)
print(z)

tf.Tensor(
[[2 3]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)
